# Functions: A function in Python is a block of reusable code that performs a specific task.
### Instead of writing the same code again and again, we can define it once and call it whenever needed.

#### Need of functions:
1. code reusability
2. Better readability
3. Modular programming

Syntax of a Function:

In [199]:
a = 10
b = 20
print(a+b)

30

In [1]:
x = 50
y = 50
print(x + y)

100

In [2]:
# Syntax for function: 

def function_name(parameters):
    # function body
    return value

function_name()

TypeError: function_name() missing 1 required positional argument: 'parameters'

In [1]:
a = 10
b = 2
c = a*b
print(c)

20

In [4]:
# Simple Function(without parameters)

def greet():
    print("hello, Good Morning everyone")

greet()

hello, Good Morning everyone

In [6]:
def multiplication(x,y):
    print(x * y)

multiplication(5,2)

10

In [8]:
def add(a,b):
    print(a + b)

add(100,200)

300

In [9]:
add(90,150)

240

In [10]:
add(200,300)

500

In [11]:
multiplication(7,2)

14

In [12]:
# Function with return value: return sends result back to caller

def sqaure(num):
    return num * num

result = sqaure(5)
print(result)

25

In [15]:
# Function with default parameter:

def greet(name="User"):
    print("Hello", name)

greet("ajit")

Hello ajit

In [17]:
# Functions with multiple return values:

def calculate(a,b):
    return a+b, a-b, a*b

x, y, z = calculate(10,5)
print(x,y,z)

15 5 50

In [18]:
# Function with *args (Variable arguments):

def total_sum(*numbers):
    total = 0
    for n in numbers:
        total += n

    return total

In [19]:
print(total_sum(50,20,10,25,35,65,75))

280

In [213]:
# Function with **kwargs(keyword arguments):

def student_info(**details):
    for key, value in details.items():
        print(key, ":", value)

In [214]:
student_info(name="Amit", age=22, course="Python")

name : Amit
age : 22
course : Python

In [20]:
# lambda Function(Anonymous Function): 
# one-line function, it will not require def keyword, 
# use for short operations

square = lambda x:x * x
print(sqaure(5))

25

In [6]:
# lambda to add two numbers:

add = lambda a,b : a + b
print(add(50,500))

550

In [24]:
# Lambda function to check even or odd numbers:

even_odd = lambda x: "Even" if x % 2 == 0 else "Odd"
print(even_odd(8))

Even

In [10]:
# Lambda with one argument

square = lambda x : x * x
print(square(9))

81

In [220]:
# Lambda with map() : Square of list elements
# map() applies lambda to each element

numbers = [1,2,3,4]

squares = list(map(lambda x: x*x, numbers))
print(squares)

[1, 4, 9, 16]

In [10]:
# filter() - Even numbers from list

numbers = [1,2,3,4,5,6,7,8,9,10]

even = list(filter(lambda x: x%2==0, numbers))
print(even)

[2, 4, 6, 8, 10]

In [12]:
from functools import reduce

numbers = [1,2,3,4]

total = reduce(lambda a,b : a+b, numbers,10)
print(total)

20

In [1]:
# Numpy: Numerical Python 
# !pip installation <library name>
import numpy

In [2]:
import numpy as np

In [3]:
age = np.array([24,28,32,34,36])
age

array([24, 28, 32, 34, 36])

In [4]:
age = np.array([[24],[28],[32],[34],[36]])
age

array([[24],
       [28],
       [32],
       [34],
       [36]])

In [5]:
type(age)

numpy.ndarray

In [7]:
data = np.array([[24,170,84,100],[28,168,80,120],[32,171,75,105],[34,170,78,108]])
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108]])

In [8]:
data.ndim

2

In [9]:
# we can fetch out elements from numpy array with the help of slicing.
# In numpy we can use with the help of row and column form [row,columns]

data[:,0:1]  # age column(first column)

array([[24],
       [28],
       [32],
       [34]])

In [11]:
data[:,2:3]

array([[84],
       [80],
       [75],
       [78]])

In [264]:
data[:,0:2]

array([[ 24, 170],
       [ 28, 168],
       [ 32, 171],
       [ 34, 170]])

In [265]:
np.mean(data[:,0:1])

np.float64(29.5)

In [266]:
# performing math computation on specific column:

print("Mean: ", np.mean(data[:, 0:1]))
print("Median: ", np.median(data[:, 0:1]))
print("Standard deviation: ", np.std(data[:, 0:1]))
print("Variance: ", np.var(data[:, 0:1]))

Mean:  29.5
Median:  30.0
Standard deviation:  3.840572873934304
Variance:  14.75

In [12]:
dir(numpy)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfortranarray',
 'asin',
 'asinh',
 'asmatrix',
 'astype',
 'atan',
 'atan2',
 'atanh',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_count',
 'bitwise_invert',
 'bitwise_left_shift',
 'bitwise_not',
 'bitwise_or',
 'bitwise_right_shift',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_shapes',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'bytes_',
 'c_',
 'can_cast',
 'cbrt',
 'cdouble',
 'ceil',
 'char',
 'character',
 'choose',
 'clip',
 'clongdouble',
 'column_stack',
 'common_type',
 'complex128',
 'complex64',
 'complexfloating',
 'compress',
 'concat',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumsum',
 'cumulative_prod',
 'cumulative_sum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'divide',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'dtypes',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exceptions',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'f2py',
 'fabs',
 'fft',
 'fill_diagonal',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float16',
 'float32',
 'float64',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'frexp',
 'from_dlpack',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'inner',
 'insert',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isdtype',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issubdtype',
 'iterable',
 'ix_',
 'kaiser',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'long',
 'longdouble',
 'longlong',
 'ma',
 'mask_indices',
 'matmul',
 'matrix',
 'matrix_transpose',
 'matvec',
 'max',
 'maximum',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mod',
 'modf',
 'moveaxis',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'ndarray',
 'ndenumerate',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'number',
 'object_',
 'ogrid',
 'ones',
 'ones_like',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'permute_dims',
 'pi',
 'piecewise',
 'place',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'pow',
 'power',
 'printoptions',
 'prod',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'row_stack',
 's_',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctypeDict',
 'searchsorted',
 'select',
 'set_printoptions',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'show_runtime',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'sinh',
 'size',
 'sort',
 'sort_complex',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str_',
 'strings',
 'subtract',
 'sum',
 'swapaxes',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'transpose',
 'trapezoid',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typecodes',
 'typename',
 'typing',
 'ubyte',
 'ufunc',
 'uint',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulong',
 'ulonglong',
 'union1d',
 'unique',
 'unique_all',
 'unique_counts',
 'unique_inverse',
 'unique_values',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unstack',
 'unwrap',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vecdot',
 'vecmat',
 'vectorize',
 'void',
 'vsplit',
 'vstack',
 'where',
 'zeros',
 'zeros_like']

In [268]:
data[:, 0:3:2]  # dropping 1st columnby using step

array([[24, 84],
       [28, 80],
       [32, 75],
       [34, 78]])

In [19]:
# creating the data in 1D

x1 = np.random.randint(10,20, size=6)  # random= function to collect random values, randint = collect random values but that
x1                                     # into int datatype only

array([14, 17, 12, 16, 11, 14], dtype=int32)

In [20]:
x1.ndim

1

In [21]:
# 2D array:

x2 = np.random.randint(10,40, size=(3,4))
x2

array([[16, 11, 28, 25],
       [33, 14, 18, 25],
       [22, 10, 18, 36]], dtype=int32)

In [22]:
x2.ndim

2

In [23]:
# Creating the data in 3D:

x3 = np.random.randint(10,50, size=(2,3,4))
x3

array([[[30, 24, 28, 20],
        [10, 41, 24, 34],
        [40, 37, 40, 29]],

       [[44, 16, 26, 23],
        [14, 25, 13, 30],
        [13, 41, 28, 12]]], dtype=int32)

In [24]:
x3.ndim

3

In [30]:
x3.size

24

In [31]:
x3.shape

(2, 3, 4)

In [275]:
data

array([[ 24, 170,  84, 100],
       [ 28, 168,  80, 120],
       [ 32, 171,  75, 105],
       [ 34, 170,  78, 108]])

In [276]:
import pandas as pd

In [277]:
df = pd.DataFrame(data)
df

    0    1   2    3
0  24  170  84  100
1  28  168  80  120
2  32  171  75  105
3  34  170  78  108

In [278]:
df.columns = ["Age","Height","Weight","BP"]
df

   Age  Height  Weight   BP
0   24     170      84  100
1   28     168      80  120
2   32     171      75  105
3   34     170      78  108

In [279]:
df.index = ['a','b','c','d']
df

   Age  Height  Weight   BP
a   24     170      84  100
b   28     168      80  120
c   32     171      75  105
d   34     170      78  108

In [280]:
print("Mean: ", df['BP'].mean())
print("Median: ", df['BP'].median())
print("Mode: ", df['BP'].mode())
print("standard deviation: ", df['BP'].std())
print("Variance: ", df['BP'].var())

Mean:  108.25
Median:  106.5
Mode:  0    100
1    105
2    108
3    120
Name: BP, dtype: int64
standard deviation:  8.5
Variance:  72.25

In [281]:
import numpy as np

In [282]:
array_1 = np.array([[1,2,3],[4,5,6]])
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [283]:
# There are attributes of numpy library
# 1. shape
# 2. size
# 3. dtype
# 4. astype
# 5. ndim

In [287]:
print(array_1.shape) # Return number of rows and number of columns
print(array_1.size)   # Number of elements in array
print(array_1.dtype)  # It will return datatype of array
print(array_1.ndim)   # It will return dimension if array

(2, 3)
6
int64
2

In [288]:
array_2 = array_1.astype('float')  # It will change the datatype of existing array.
array_2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [289]:
np.log10(100)

np.float64(2.0)

In [290]:
np.log(10)

np.float64(2.302585092994046)

In [291]:
np.log(1)

np.float64(0.0)

In [292]:
np.tanh(45)

np.float64(1.0)

In [293]:
np.sin(array_1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [294]:
np.nan

nan

In [296]:
np.array([np.nan, 12,34])

array([nan, 12., 34.])

In [297]:
np.sqrt(144)

np.float64(12.0)

In [299]:
np.absolute(-90)

np.int64(90)

In [33]:
np.round(3.6754323,1)

np.float64(3.7)

In [34]:
np.power(34.908,2)

np.float64(1218.5684640000002)

# Pandas Library:

In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("nyc_weather (1).csv")
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [306]:
df.info() # It will return entire variable information of datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EST                   31 non-null     object
 1   Temperature           31 non-null     int64
 2   DewPoint              31 non-null     int64
 3   Humidity              31 non-null     int64
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64
 6   WindSpeedMPH          31 non-null     int64
 7   PrecipitationIn       31 non-null     object
 8   CloudCover            31 non-null     int64
 9   Events                9 non-null      object
 10  WindDirDegrees        31 non-null     int64
dtypes: float64(1), int64(7), object(3)
memory usage: 2.8+ KB

In [307]:
df.head() # It will return first five rows entries

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333

In [37]:
df.head(25)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286

In [309]:
df.tail() # It will return last 5 rows

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [310]:
df.tail(10)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [311]:
df.describe() # Retrun all mathematical computation on each variable

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.903226,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.724639,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,7.000000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [312]:
df["Temperature"].describe()

count    31.000000
mean     34.677419
std       7.639315
min      20.000000
25%      29.000000
50%      35.000000
75%      39.500000
max      50.000000
Name: Temperature, dtype: float64

In [314]:
df[["Temperature","DewPoint","Humidity","VisibilityMiles"]]

    Temperature  DewPoint  Humidity  VisibilityMiles
0            38        23        52               10
1            36        18        46               10
2            40        21        47               10
3            25         9        44               10
4            20        -3        41               10
5            33         4        35               10
6            39        11        33               10
7            39        29        64               10
8            44        38        77                9
9            50        46        71                4
10           33         8        37               10
11           35        15        53               10
12           26         4        42               10
13           30        12        47               10
14           43        31        62                9
15           47        37        70                8
16           36        23        66                8
17           25         6        53                9
18           22         3        42               10
19           32        15        49               10
20           31        11        45               10
21           26         6        41                9
22           26        21        78                1
23           28        11        53                8
24           34        18        54               10
25           43        29        56               10
26           41        22        45               10
27           37        20        51               10
28           36        21        50               10
29           34        16        46               10
30           46        28        52               10

In [315]:
df[["Temperature","DewPoint","Humidity","VisibilityMiles"]].describe()

       Temperature   DewPoint   Humidity  VisibilityMiles
count    31.000000  31.000000  31.000000        31.000000
mean     34.677419  17.838710  51.677419         9.193548
std       7.639315  11.378626  11.634395         1.939405
min      20.000000  -3.000000  33.000000         1.000000
25%      29.000000  10.000000  44.500000         9.000000
50%      35.000000  18.000000  50.000000        10.000000
75%      39.500000  23.000000  55.000000        10.000000
max      50.000000  46.000000  78.000000        10.000000

In [317]:
df["Temperature"].head()

0    38
1    36
2    40
3    25
4    20
Name: Temperature, dtype: int64

In [319]:
df[["Temperature","DewPoint"]].head(11)

    Temperature  DewPoint
0            38        23
1            36        18
2            40        21
3            25         9
4            20        -3
5            33         4
6            39        11
7            39        29
8            44        38
9            50        46
10           33         8

In [320]:
import numpy as np

In [321]:
arr = np.random.randint(1,100,(10,2))
arr

array([[26,  7],
       [29, 26],
       [71, 17],
       [ 2, 25],
       [ 9, 98],
       [11, 84],
       [54, 41],
       [44, 79],
       [34, 66],
       [ 5,  6]], dtype=int32)

In [322]:
df = pd.DataFrame(arr,columns = ["X","Y"])
df

    X   Y
0  26   7
1  29  26
2  71  17
3   2  25
4   9  98
5  11  84
6  54  41
7  44  79
8  34  66
9   5   6

In [323]:
data = np.random.randint(1,100,10)
data

array([81, 38,  8, 38, 48, 35, 44, 23, 21, 23], dtype=int32)

In [324]:
type(data)

numpy.ndarray

In [325]:
ser = pd.Series(data)
ser

0    81
1    38
2     8
3    38
4    48
5    35
6    44
7    23
8    21
9    23
dtype: int32

In [326]:
ser.dtype

dtype('int32')

In [327]:
ser.mean()

np.float64(35.9)

In [328]:
ser.mode()

0    23
1    38
dtype: int32

In [329]:
ser.var()

398.76666666666665

In [330]:
ser.kurtosis()

np.float64(2.349878128536586)

In [331]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [333]:
pd.DataFrame(np.random.randint(1,100,size=(10,5)))

    0   1   2   3   4
0  87  16  79  16  74
1  48  29  39  54  88
2   5  99  34  27  24
3  64  93  45  34  47
4  15  33  35  13   8
5  63  11   4  29  46
6   5  48  93  90  46
7  60  35  58  22  40
8  58  21  82  80  63
9  55  38  47  56  45

In [334]:
# List to dataframe

lst1 = [
    [101,"F",12,120],
    [102,"M",13,124],
    [103,"F",12,100],
    [104,"M",12,110],
    [105,"F",np.nan,120]
]

In [335]:
lst1

[[101, 'F', 12, 120],
 [102, 'M', 13, 124],
 [103, 'F', 12, 100],
 [104, 'M', 12, 110],
 [105, 'F', nan, 120]]

In [336]:
df1 = pd.DataFrame(lst1)
df1

     0  1     2    3
0  101  F  12.0  120
1  102  M  13.0  124
2  103  F  12.0  100
3  104  M  12.0  110
4  105  F   NaN  120

In [337]:
df1.columns = ["ID","Gender","Age","Height"]

In [338]:
df1

    ID Gender   Age  Height
0  101      F  12.0     120
1  102      M  13.0     124
2  103      F  12.0     100
3  104      M  12.0     110
4  105      F   NaN     120

In [339]:
df1.isnull().sum()

ID        0
Gender    0
Age       1
Height    0
dtype: int64

In [340]:
# Pandas Attribute:

In [341]:
import pandas as pd

nyc = pd.read_csv("nyc_weather (1).csv")
nyc

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,01-01-2016,38,23,52,30.03,10,8,0,5,NaN,281
1,01-02-2016,36,18,46,30.02,10,7,0,3,NaN,275
2,01-03-2016,40,21,47,29.86,10,8,0,1,NaN,277
3,01-04-2016,25,9,44,30.05,10,9,0,3,NaN,345
4,01-05-2016,20,-3,41,30.57,10,5,0,0,NaN,333
5,01-06-2016,33,4,35,30.50,10,4,0,0,NaN,259
6,01-07-2016,39,11,33,30.28,10,2,0,3,NaN,293
7,01-08-2016,39,29,64,30.20,10,4,0,8,NaN,79
8,01-09-2016,44,38,77,30.16,9,8,T,8,Rain,76
9,01-10-2016,50,46,71,29.59,4,7,1.8,7,Rain,109
10,01-11-2016,33,8,37,29.92,10,7,0,1,NaN,289
11,01-12-2016,35,15,53,29.85,10,6,T,4,NaN,235
12,01-13-2016,26,4,42,29.94,10,10,0,0,NaN,284
13,01-14-2016,30,12,47,29.95,10,5,T,7,NaN,266
14,01-15-2016,43,31,62,29.82,9,5,T,2,NaN,101
15,01-16-2016,47,37,70,29.52,8,7,0.24,7,Rain,340
16,01-17-2016,36,23,66,29.78,8,6,0.05,6,Fog-Snow,345
17,01-18-2016,25,6,53,29.83,9,12,T,2,Snow,293
18,01-19-2016,22,3,42,30.03,10,11,0,1,NaN,293
19,01-20-2016,32,15,49,30.13,10,6,0,2,NaN,302
20,01-21-2016,31,11,45,30.15,10,6,0,1,NaN,312
21,01-22-2016,26,6,41,30.21,9,7,0.01,3,Snow,34
22,01-23-2016,26,21,78,29.77,1,16,2.31,8,Fog-Snow,42
23,01-24-2016,28,11,53,29.92,8,6,T,3,Snow,327
24,01-25-2016,34,18,54,30.25,10,3,0,2,NaN,286
25,01-26-2016,43,29,56,30.03,10,7,0,2,NaN,244
26,01-27-2016,41,22,45,30.03,10,7,T,3,Rain,311
27,01-28-2016,37,20,51,29.90,10,5,0,1,NaN,234
28,01-29-2016,36,21,50,29.58,10,8,0,4,NaN,298
29,01-30-2016,34,16,46,30.01,10,7,0,0,NaN,257
30,01-31-2016,46,28,52,29.90,10,5,0,0,NaN,241

In [342]:
nyc.columns  # Return column names

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [343]:
nyc.index

RangeIndex(start=0, stop=31, step=1)

In [344]:
nyc.values

array([['01-01-2016', 38, 23, 52, 30.03, 10, 8, '0', 5, nan, 281],
       ['01-02-2016', 36, 18, 46, 30.02, 10, 7, '0', 3, nan, 275],
       ['01-03-2016', 40, 21, 47, 29.86, 10, 8, '0', 1, nan, 277],
       ['01-04-2016', 25, 9, 44, 30.05, 10, 9, '0', 3, nan, 345],
       ['01-05-2016', 20, -3, 41, 30.57, 10, 5, '0', 0, nan, 333],
       ['01-06-2016', 33, 4, 35, 30.5, 10, 4, '0', 0, nan, 259],
       ['01-07-2016', 39, 11, 33, 30.28, 10, 2, '0', 3, nan, 293],
       ['01-08-2016', 39, 29, 64, 30.2, 10, 4, '0', 8, nan, 79],
       ['01-09-2016', 44, 38, 77, 30.16, 9, 8, 'T', 8, 'Rain', 76],
       ['01-10-2016', 50, 46, 71, 29.59, 4, 7, '1.8', 7, 'Rain', 109],
       ['01-11-2016', 33, 8, 37, 29.92, 10, 7, '0', 1, nan, 289],
       ['01-12-2016', 35, 15, 53, 29.85, 10, 6, 'T', 4, nan, 235],
       ['01-13-2016', 26, 4, 42, 29.94, 10, 10, '0', 0, nan, 284],
       ['01-14-2016', 30, 12, 47, 29.95, 10, 5, 'T', 7, nan, 266],
       ['01-15-2016', 43, 31, 62, 29.82, 9, 5, 'T', 2, nan, 101],
       ['01-16-2016', 47, 37, 70, 29.52, 8, 7, '0.24', 7, 'Rain', 340],
       ['01-17-2016', 36, 23, 66, 29.78, 8, 6, '0.05', 6, 'Fog-Snow',
        345],
       ['01-18-2016', 25, 6, 53, 29.83, 9, 12, 'T', 2, 'Snow', 293],
       ['01-19-2016', 22, 3, 42, 30.03, 10, 11, '0', 1, nan, 293],
       ['01-20-2016', 32, 15, 49, 30.13, 10, 6, '0', 2, nan, 302],
       ['01-21-2016', 31, 11, 45, 30.15, 10, 6, '0', 1, nan, 312],
       ['01-22-2016', 26, 6, 41, 30.21, 9, 7, '0.01', 3, 'Snow', 34],
       ['01-23-2016', 26, 21, 78, 29.77, 1, 16, '2.31', 8, 'Fog-Snow',
        42],
       ['01-24-2016', 28, 11, 53, 29.92, 8, 6, 'T', 3, 'Snow', 327],
       ['01-25-2016', 34, 18, 54, 30.25, 10, 3, '0', 2, nan, 286],
       ['01-26-2016', 43, 29, 56, 30.03, 10, 7, '0', 2, nan, 244],
       ['01-27-2016', 41, 22, 45, 30.03, 10, 7, 'T', 3, 'Rain', 311],
       ['01-28-2016', 37, 20, 51, 29.9, 10, 5, '0', 1, nan, 234],
       ['01-29-2016', 36, 21, 50, 29.58, 10, 8, '0', 4, nan, 298],
       ['01-30-2016', 34, 16, 46, 30.01, 10, 7, '0', 0, nan, 257],
       ['01-31-2016', 46, 28, 52, 29.9, 10, 5, '0', 0, nan, 241]],
      dtype=object)

In [345]:
nyc.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH              int64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [346]:
nyc.shape

(31, 11)

In [347]:
nyc.axes

[RangeIndex(start=0, stop=31, step=1),
 Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
        'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
        'Events', 'WindDirDegrees'],
       dtype='object')]

In [348]:
nyc.ndim

2

In [350]:
nyc["Temperature"].unique()

array([38, 36, 40, 25, 20, 33, 39, 44, 50, 35, 26, 30, 43, 47, 22, 32, 31,
       28, 34, 41, 37, 46])

In [351]:
nyc["Temperature"].nunique()

22

In [352]:
nyc.select_dtypes(include=["float64","object"])

           EST  Sea Level PressureIn PrecipitationIn    Events
0   01-01-2016                 30.03               0       NaN
1   01-02-2016                 30.02               0       NaN
2   01-03-2016                 29.86               0       NaN
3   01-04-2016                 30.05               0       NaN
4   01-05-2016                 30.57               0       NaN
5   01-06-2016                 30.50               0       NaN
6   01-07-2016                 30.28               0       NaN
7   01-08-2016                 30.20               0       NaN
8   01-09-2016                 30.16               T      Rain
9   01-10-2016                 29.59             1.8      Rain
10  01-11-2016                 29.92               0       NaN
11  01-12-2016                 29.85               T       NaN
12  01-13-2016                 29.94               0       NaN
13  01-14-2016                 29.95               T       NaN
14  01-15-2016                 29.82               T       NaN
15  01-16-2016                 29.52            0.24      Rain
16  01-17-2016                 29.78            0.05  Fog-Snow
17  01-18-2016                 29.83               T      Snow
18  01-19-2016                 30.03               0       NaN
19  01-20-2016                 30.13               0       NaN
20  01-21-2016                 30.15               0       NaN
21  01-22-2016                 30.21            0.01      Snow
22  01-23-2016                 29.77            2.31  Fog-Snow
23  01-24-2016                 29.92               T      Snow
24  01-25-2016                 30.25               0       NaN
25  01-26-2016                 30.03               0       NaN
26  01-27-2016                 30.03               T      Rain
27  01-28-2016                 29.90               0       NaN
28  01-29-2016                 29.58               0       NaN
29  01-30-2016                 30.01               0       NaN
30  01-31-2016                 29.90               0       NaN

In [357]:
nyc_obj = nyc.select_dtypes(include="object")
nyc_obj.tail(10)

           EST PrecipitationIn    Events
21  01-22-2016            0.01      Snow
22  01-23-2016            2.31  Fog-Snow
23  01-24-2016               T      Snow
24  01-25-2016               0       NaN
25  01-26-2016               0       NaN
26  01-27-2016               T      Rain
27  01-28-2016               0       NaN
28  01-29-2016               0       NaN
29  01-30-2016               0       NaN
30  01-31-2016               0       NaN