In [2]:
import pandas as pd

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [3]:
# First upload Salaries.csv
#df=pd.read_csv("Salaries.csv")
df=pd.read_csv("Salaries.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        51 non-null     object
 1   discipline  51 non-null     object
 2   phd         51 non-null     int64
 3   service     51 non-null     int64
 4   sex         51 non-null     object
 5   salary      51 non-null     int64
dtypes: int64(3), object(3)
memory usage: 2.5+ KB

In [4]:
df.head()  # It will retun first 5 rows

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [5]:
df.head(15)

         rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   20       20  Male  122400
2   AssocProf          A   20       17  Male   81285
3        Prof          B   23       23  Male  134778
4    AsstProf          B    1        0  Male   88000
5        Prof          B   17        3  Male  150480
6    AsstProf          B    8        3  Male   75044
7    AsstProf          B    4        0  Male   92000
8        Prof          A   19        7  Male  107300
9        Prof          A   29       27  Male  150500
10   AsstProf          B    4        4  Male   92000
11       Prof          A   33       30  Male  103106
12   AsstProf          A    4        2  Male   73000
13   AsstProf          A    2        0  Male   85000
14       Prof          A   30       23  Male   91100

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        51 non-null     object
 1   discipline  51 non-null     object
 2   phd         51 non-null     int64
 3   service     51 non-null     int64
 4   sex         51 non-null     object
 5   salary      51 non-null     int64
dtypes: int64(3), object(3)
memory usage: 2.5+ KB

In [7]:
df.tail()

         rank discipline  phd  service     sex  salary
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954
50       Prof          A   23       15  Female  109646

In [8]:
df.tail(20)

         rank discipline  phd  service     sex  salary
31   AsstProf          A    5        3  Female   73500
32   AsstProf          A    3        1  Female   72500
33       Prof          B   36       26  Female  144651
34  AssocProf          B   12       10  Female  103994
35   AsstProf          B    3        3  Female   92000
36       Prof          A   29       27  Female   91000
37  AssocProf          A   26       24  Female   73300
38       Prof          A   36       19  Female  117555
39   AsstProf          A    7        6  Female   63100
40       Prof          A   17       11  Female   90450
41   AsstProf          A    4        2  Female   77500
42       Prof          A   28        7  Female  116450
43   AsstProf          A    8        3  Female   78500
44  AssocProf          B   12        9  Female   71065
45       Prof          B   24       15  Female  161101
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954
50       Prof          A   23       15  Female  109646

In [9]:
df.describe() # It will return all statistical calculations

             phd    service         salary
count  51.000000  51.000000      51.000000
mean   17.705882  12.960784  106278.568627
std    12.090152  11.615439   27957.854794
min     1.000000   0.000000   63100.000000
25%     8.000000   3.000000   86500.000000
50%    17.000000  10.000000  103994.000000
75%    24.500000  20.000000  123041.500000
max    56.000000  49.000000  186960.000000

In [10]:
df.columns  # It will return only column names from dataframe

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [11]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [12]:
df.tail(10)

         rank discipline  phd  service     sex  salary
41   AsstProf          A    4        2  Female   77500
42       Prof          A   28        7  Female  116450
43   AsstProf          A    8        3  Female   78500
44  AssocProf          B   12        9  Female   71065
45       Prof          B   24       15  Female  161101
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954
50       Prof          A   23       15  Female  109646

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        51 non-null     object
 1   discipline  51 non-null     object
 2   phd         51 non-null     int64
 3   service     51 non-null     int64
 4   sex         51 non-null     object
 5   salary      51 non-null     int64
dtypes: int64(3), object(3)
memory usage: 2.5+ KB

In [14]:
df['rank']

0          Prof
1          Prof
2     AssocProf
3          Prof
4      AsstProf
5          Prof
6      AsstProf
7      AsstProf
8          Prof
9          Prof
10     AsstProf
11         Prof
12     AsstProf
13     AsstProf
14         Prof
15     AsstProf
16         Prof
17    AssocProf
18         Prof
19    AssocProf
20         Prof
21     AsstProf
22         Prof
23    AssocProf
24         Prof
25     AsstProf
26    AssocProf
27         Prof
28     AsstProf
29         Prof
30         Prof
31     AsstProf
32     AsstProf
33         Prof
34    AssocProf
35     AsstProf
36         Prof
37    AssocProf
38         Prof
39     AsstProf
40         Prof
41     AsstProf
42         Prof
43     AsstProf
44    AssocProf
45         Prof
46         Prof
47    AssocProf
48         Prof
49         Prof
50         Prof
Name: rank, dtype: object

In [15]:
df['sex']

0       Male
1       Male
2       Male
3       Male
4       Male
5       Male
6       Male
7       Male
8       Male
9       Male
10      Male
11      Male
12      Male
13      Male
14      Male
15      Male
16      Male
17      Male
18      Male
19      Male
20      Male
21      Male
22    Female
23    Female
24    Female
25    Female
26    Female
27    Female
28    Female
29    Female
30    Female
31    Female
32    Female
33    Female
34    Female
35    Female
36    Female
37    Female
38    Female
39    Female
40    Female
41    Female
42    Female
43    Female
44    Female
45    Female
46    Female
47    Female
48    Female
49    Female
50    Female
Name: sex, dtype: object

In [5]:
df['discipline']

0     B
1     A
2     A
3     B
4     B
5     B
6     B
7     B
8     A
9     A
10    B
11    A
12    A
13    A
14    A
15    B
16    B
17    B
18    B
19    B
20    B
21    B
22    A
23    A
24    B
25    B
26    B
27    B
28    B
29    B
30    A
31    A
32    A
33    B
34    B
35    B
36    A
37    A
38    A
39    A
40    A
41    A
42    A
43    A
44    B
45    B
46    B
47    B
48    B
49    A
50    A
Name: discipline, dtype: object

In [6]:
df.describe()

             phd    service         salary
count  51.000000  51.000000      51.000000
mean   17.705882  12.960784  106278.568627
std    12.090152  11.615439   27957.854794
min     1.000000   0.000000   63100.000000
25%     8.000000   3.000000   86500.000000
50%    17.000000  10.000000  103994.000000
75%    24.500000  20.000000  123041.500000
max    56.000000  49.000000  186960.000000

In [7]:
df.max()

rank            Prof
discipline         B
phd               56
service           49
sex             Male
salary        186960
dtype: object

In [8]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            63100
dtype: object

In [9]:
df.phd.mean()

np.float64(17.705882352941178)

In [10]:
df.phd.describe()

count    51.000000
mean     17.705882
std      12.090152
min       1.000000
25%       8.000000
50%      17.000000
75%      24.500000
max      56.000000
Name: phd, dtype: float64

In [11]:
df.phd.quantile(0.25)

np.float64(8.0)

In [12]:
df.salary.quantile(0.50)

np.float64(103994.0)

In [13]:
df.salary.quantile(0.75)

np.float64(123041.5)

In [14]:
df.phd.std()

12.090151558433103

In [15]:
df_50=df.head(50)

In [16]:
df_50.salary.mean()

np.float64(106211.22)

In [17]:
df_50

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   20       20    Male  122400
2   AssocProf          A   20       17    Male   81285
3        Prof          B   23       23    Male  134778
4    AsstProf          B    1        0    Male   88000
5        Prof          B   17        3    Male  150480
6    AsstProf          B    8        3    Male   75044
7    AsstProf          B    4        0    Male   92000
8        Prof          A   19        7    Male  107300
9        Prof          A   29       27    Male  150500
10   AsstProf          B    4        4    Male   92000
11       Prof          A   33       30    Male  103106
12   AsstProf          A    4        2    Male   73000
13   AsstProf          A    2        0    Male   85000
14       Prof          A   30       23    Male   91100
15   AsstProf          B    7        2    Male   91300
16       Prof          B   21       20    Male  123683
17  AssocProf          B    9        7    Male  107008
18       Prof          B   22       21    Male  155750
19  AssocProf          B   12        8    Male  119800
20       Prof          B   45       45    Male  146856
21   AsstProf          B    4        3    Male   91000
22       Prof          A   39       36  Female  137000
23  AssocProf          A   13        8  Female   74830
24       Prof          B   25       25  Female  140096
25   AsstProf          B   11        3  Female   74692
26  AssocProf          B   11       11  Female  103613
27       Prof          B   17       17  Female  111512
28   AsstProf          B   10        5  Female   97032
29       Prof          B   20       14  Female  127512
30       Prof          A   12        0  Female  105000
31   AsstProf          A    5        3  Female   73500
32   AsstProf          A    3        1  Female   72500
33       Prof          B   36       26  Female  144651
34  AssocProf          B   12       10  Female  103994
35   AsstProf          B    3        3  Female   92000
36       Prof          A   29       27  Female   91000
37  AssocProf          A   26       24  Female   73300
38       Prof          A   36       19  Female  117555
39   AsstProf          A    7        6  Female   63100
40       Prof          A   17       11  Female   90450
41   AsstProf          A    4        2  Female   77500
42       Prof          A   28        7  Female  116450
43   AsstProf          A    8        3  Female   78500
44  AssocProf          B   12        9  Female   71065
45       Prof          B   24       15  Female  161101
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954

In [18]:
#Selecting a column
df.salary # does not work if column name contains blank space or dot (eg. "No. of Columns")
#           for that enclose column name inside square bracket.

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [19]:
df['salary'] # will work if column name has blank space or dot eg. df["No. of Columns"]

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [20]:
result1=df.salary
result1

0     186960
1     122400
2      81285
3     134778
4      88000
5     150480
6      75044
7      92000
8     107300
9     150500
10     92000
11    103106
12     73000
13     85000
14     91100
15     91300
16    123683
17    107008
18    155750
19    119800
20    146856
21     91000
22    137000
23     74830
24    140096
25     74692
26    103613
27    111512
28     97032
29    127512
30    105000
31     73500
32     72500
33    144651
34    103994
35     92000
36     91000
37     73300
38    117555
39     63100
40     90450
41     77500
42    116450
43     78500
44     71065
45    161101
46    105450
47    104542
48    124312
49    109954
50    109646
Name: salary, dtype: int64

In [21]:

type(result1)

pandas.core.series.Series

In [22]:
result2=df[['salary','rank']]

In [23]:
result2

    salary       rank
0   186960       Prof
1   122400       Prof
2    81285  AssocProf
3   134778       Prof
4    88000   AsstProf
5   150480       Prof
6    75044   AsstProf
7    92000   AsstProf
8   107300       Prof
9   150500       Prof
10   92000   AsstProf
11  103106       Prof
12   73000   AsstProf
13   85000   AsstProf
14   91100       Prof
15   91300   AsstProf
16  123683       Prof
17  107008  AssocProf
18  155750       Prof
19  119800  AssocProf
20  146856       Prof
21   91000   AsstProf
22  137000       Prof
23   74830  AssocProf
24  140096       Prof
25   74692   AsstProf
26  103613  AssocProf
27  111512       Prof
28   97032   AsstProf
29  127512       Prof
30  105000       Prof
31   73500   AsstProf
32   72500   AsstProf
33  144651       Prof
34  103994  AssocProf
35   92000   AsstProf
36   91000       Prof
37   73300  AssocProf
38  117555       Prof
39   63100   AsstProf
40   90450       Prof
41   77500   AsstProf
42  116450       Prof
43   78500   AsstProf
44   71065  AssocProf
45  161101       Prof
46  105450       Prof
47  104542  AssocProf
48  124312       Prof
49  109954       Prof
50  109646       Prof

In [24]:
type(result2)

pandas.core.frame.DataFrame

In [25]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [26]:
# Extract particular columns in a new dataframe
newdf=df[['salary','service','phd']]
newdf

    salary  service  phd
0   186960       49   56
1   122400       20   20
2    81285       17   20
3   134778       23   23
4    88000        0    1
5   150480        3   17
6    75044        3    8
7    92000        0    4
8   107300        7   19
9   150500       27   29
10   92000        4    4
11  103106       30   33
12   73000        2    4
13   85000        0    2
14   91100       23   30
15   91300        2    7
16  123683       20   21
17  107008        7    9
18  155750       21   22
19  119800        8   12
20  146856       45   45
21   91000        3    4
22  137000       36   39
23   74830        8   13
24  140096       25   25
25   74692        3   11
26  103613       11   11
27  111512       17   17
28   97032        5   10
29  127512       14   20
30  105000        0   12
31   73500        3    5
32   72500        1    3
33  144651       26   36
34  103994       10   12
35   92000        3    3
36   91000       27   29
37   73300       24   26
38  117555       19   36
39   63100        6    7
40   90450       11   17
41   77500        2    4
42  116450        7   28
43   78500        3    8
44   71065        9   12
45  161101       15   24
46  105450       10   18
47  104542        6   19
48  124312       17   17
49  109954       14   28
50  109646       15   23

In [27]:
df['discipline'].value_counts() # category and its value

discipline
B    28
A    23
Name: count, dtype: int64

In [28]:
df['rank'].value_counts()

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [37]:
df.groupby(['rank']).salary.mean()

rank
AssocProf     93270.777778
AsstProf      82260.500000
Prof         125561.615385
Name: salary, dtype: float64

In [35]:

df.groupby(['rank','discipline']).count()

                      phd  service  sex  salary
rank      discipline
AssocProf A             3        3    3       3
          B             6        6    6       6
AsstProf  A             7        7    7       7
          B             9        9    9       9
Prof      A            13       13   13      13
          B            13       13   13      13

In [30]:
df.groupby(["discipline"]).count()

            rank  phd  service  sex  salary
discipline
A             23   23       23   23      23
B             28   28       28   28      28

In [31]:
df.groupby(["discipline","rank"]).count() # It will return count of each category depending on dicipline and rank clm

                      phd  service  sex  salary
discipline rank
A          AssocProf    3        3    3       3
           AsstProf     7        7    7       7
           Prof        13       13   13      13
B          AssocProf    6        6    6       6
           AsstProf     9        9    9       9
           Prof        13       13   13      13

In [39]:
df.groupby(["discipline","rank","sex"])[['phd','service']].count()

                             phd  service
discipline rank      sex
A          AssocProf Female    2        2
                     Male      1        1
           AsstProf  Female    5        5
                     Male      2        2
           Prof      Female    8        8
                     Male      5        5
B          AssocProf Female    4        4
                     Male      2        2
           AsstProf  Female    3        3
                     Male      6        6
           Prof      Female    7        7
                     Male      6        6

In [33]:
df.groupby(["discipline","rank","sex"]).mean() # avg sal of discipline B's Male Prof is: 137989.076923

                                   phd    service         salary
discipline rank      sex
A          AssocProf Female  19.500000  16.000000   74065.000000
                     Male    20.000000  17.000000   81285.000000
           AsstProf  Female   5.400000   3.000000   73020.000000
                     Male     3.000000   1.000000   79000.000000
           Prof      Female  26.500000  16.125000  109631.875000
                     Male    26.200000  21.400000  114881.200000
B          AssocProf Female  13.500000   9.000000   95803.500000
                     Male    10.500000   7.500000  113404.000000
           AsstProf  Female   8.000000   3.666667   87908.000000
                     Male     4.666667   2.000000   88224.000000
           Prof      Female  22.428571  17.714286  130662.000000
                     Male    30.666667  26.833333  149751.166667

In [44]:
df.groupby('rank')[['salary','phd']].mean() # group by rank and find mean of specified columns only

                  salary        phd
rank
AssocProf   93270.777778  14.888889
AsstProf    82260.500000   5.312500
Prof       125561.615385  26.307692

In [40]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
9   Prof          A   29       27    Male  150500
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
29  Prof          B   20       14  Female  127512
33  Prof          B   36       26  Female  144651
45  Prof          B   24       15  Female  161101
48  Prof          B   17       17  Female  124312

In [41]:
df.shape

(51, 6)

In [42]:
df.shape[0]

51

In [48]:
df[df.salary>120000].shape[0] # count of prof having sal > 120000

14

In [49]:
# Create a dataframe having all Males whose salary is > 1,50,000/-

newdf=df[(df['sex']=='Male') & (df['salary']>150000)]
newdf

    rank discipline  phd  service   sex  salary
0   Prof          B   56       49  Male  186960
5   Prof          B   17        3  Male  150480
9   Prof          A   29       27  Male  150500
18  Prof          B   22       21  Male  155750

In [50]:
# newdf.count()
# OR
newdf.shape[0]

4

In [51]:
df # will display all records

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   20       20    Male  122400
2   AssocProf          A   20       17    Male   81285
3        Prof          B   23       23    Male  134778
4    AsstProf          B    1        0    Male   88000
5        Prof          B   17        3    Male  150480
6    AsstProf          B    8        3    Male   75044
7    AsstProf          B    4        0    Male   92000
8        Prof          A   19        7    Male  107300
9        Prof          A   29       27    Male  150500
10   AsstProf          B    4        4    Male   92000
11       Prof          A   33       30    Male  103106
12   AsstProf          A    4        2    Male   73000
13   AsstProf          A    2        0    Male   85000
14       Prof          A   30       23    Male   91100
15   AsstProf          B    7        2    Male   91300
16       Prof          B   21       20    Male  123683
17  AssocProf          B    9        7    Male  107008
18       Prof          B   22       21    Male  155750
19  AssocProf          B   12        8    Male  119800
20       Prof          B   45       45    Male  146856
21   AsstProf          B    4        3    Male   91000
22       Prof          A   39       36  Female  137000
23  AssocProf          A   13        8  Female   74830
24       Prof          B   25       25  Female  140096
25   AsstProf          B   11        3  Female   74692
26  AssocProf          B   11       11  Female  103613
27       Prof          B   17       17  Female  111512
28   AsstProf          B   10        5  Female   97032
29       Prof          B   20       14  Female  127512
30       Prof          A   12        0  Female  105000
31   AsstProf          A    5        3  Female   73500
32   AsstProf          A    3        1  Female   72500
33       Prof          B   36       26  Female  144651
34  AssocProf          B   12       10  Female  103994
35   AsstProf          B    3        3  Female   92000
36       Prof          A   29       27  Female   91000
37  AssocProf          A   26       24  Female   73300
38       Prof          A   36       19  Female  117555
39   AsstProf          A    7        6  Female   63100
40       Prof          A   17       11  Female   90450
41   AsstProf          A    4        2  Female   77500
42       Prof          A   28        7  Female  116450
43   AsstProf          A    8        3  Female   78500
44  AssocProf          B   12        9  Female   71065
45       Prof          B   24       15  Female  161101
46       Prof          B   18       10  Female  105450
47  AssocProf          B   19        6  Female  104542
48       Prof          B   17       17  Female  124312
49       Prof          A   28       14  Female  109954
50       Prof          A   23       15  Female  109646

In [52]:
# to extract only particular index record - say 5th index record
df[5] # will raise error

KeyError: 5

In [53]:
df.iloc[77] # iloc -> index location for row

IndexError: single positional indexer is out-of-bounds

In [54]:
df.iloc[1:4, 0:3]  # row 1 to 3, col 0 to 2

        rank discipline  phd
1       Prof          A   20
2  AssocProf          A   20
3       Prof          B   23

In [55]:
df.iloc[0:10,0:3] # 0 to 9 records, 0 to 2 columns

        rank discipline  phd
0       Prof          B   56
1       Prof          A   20
2  AssocProf          A   20
3       Prof          B   23
4   AsstProf          B    1
5       Prof          B   17
6   AsstProf          B    8
7   AsstProf          B    4
8       Prof          A   19
9       Prof          A   29

In [56]:
df.iloc[0:2,] # rows 0 to 1 and all columns, Or df.iloc[0:2]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   20       20  Male  122400

In [57]:
df.iloc[:,4] #all rows, index 4 column

0       Male
1       Male
2       Male
3       Male
4       Male
5       Male
6       Male
7       Male
8       Male
9       Male
10      Male
11      Male
12      Male
13      Male
14      Male
15      Male
16      Male
17      Male
18      Male
19      Male
20      Male
21      Male
22    Female
23    Female
24    Female
25    Female
26    Female
27    Female
28    Female
29    Female
30    Female
31    Female
32    Female
33    Female
34    Female
35    Female
36    Female
37    Female
38    Female
39    Female
40    Female
41    Female
42    Female
43    Female
44    Female
45    Female
46    Female
47    Female
48    Female
49    Female
50    Female
Name: sex, dtype: object

In [58]:
df.iloc[:,0:3]

         rank discipline  phd
0        Prof          B   56
1        Prof          A   20
2   AssocProf          A   20
3        Prof          B   23
4    AsstProf          B    1
5        Prof          B   17
6    AsstProf          B    8
7    AsstProf          B    4
8        Prof          A   19
9        Prof          A   29
10   AsstProf          B    4
11       Prof          A   33
12   AsstProf          A    4
13   AsstProf          A    2
14       Prof          A   30
15   AsstProf          B    7
16       Prof          B   21
17  AssocProf          B    9
18       Prof          B   22
19  AssocProf          B   12
20       Prof          B   45
21   AsstProf          B    4
22       Prof          A   39
23  AssocProf          A   13
24       Prof          B   25
25   AsstProf          B   11
26  AssocProf          B   11
27       Prof          B   17
28   AsstProf          B   10
29       Prof          B   20
30       Prof          A   12
31   AsstProf          A    5
32   AsstProf          A    3
33       Prof          B   36
34  AssocProf          B   12
35   AsstProf          B    3
36       Prof          A   29
37  AssocProf          A   26
38       Prof          A   36
39   AsstProf          A    7
40       Prof          A   17
41   AsstProf          A    4
42       Prof          A   28
43   AsstProf          A    8
44  AssocProf          B   12
45       Prof          B   24
46       Prof          B   18
47  AssocProf          B   19
48       Prof          B   17
49       Prof          A   28
50       Prof          A   23

In [59]:
df.iloc[[10,20,22,24],] # only particular rows with all columns df.iloc[[10,20,22,24]]

        rank discipline  phd  service     sex  salary
10  AsstProf          B    4        4    Male   92000
20      Prof          B   45       45    Male  146856
22      Prof          A   39       36  Female  137000
24      Prof          B   25       25  Female  140096

In [60]:
df.loc[:,['rank','sex']] # without mentioning index no. - mention col name

         rank     sex
0        Prof    Male
1        Prof    Male
2   AssocProf    Male
3        Prof    Male
4    AsstProf    Male
5        Prof    Male
6    AsstProf    Male
7    AsstProf    Male
8        Prof    Male
9        Prof    Male
10   AsstProf    Male
11       Prof    Male
12   AsstProf    Male
13   AsstProf    Male
14       Prof    Male
15   AsstProf    Male
16       Prof    Male
17  AssocProf    Male
18       Prof    Male
19  AssocProf    Male
20       Prof    Male
21   AsstProf    Male
22       Prof  Female
23  AssocProf  Female
24       Prof  Female
25   AsstProf  Female
26  AssocProf  Female
27       Prof  Female
28   AsstProf  Female
29       Prof  Female
30       Prof  Female
31   AsstProf  Female
32   AsstProf  Female
33       Prof  Female
34  AssocProf  Female
35   AsstProf  Female
36       Prof  Female
37  AssocProf  Female
38       Prof  Female
39   AsstProf  Female
40       Prof  Female
41   AsstProf  Female
42       Prof  Female
43   AsstProf  Female
44  AssocProf  Female
45       Prof  Female
46       Prof  Female
47  AssocProf  Female
48       Prof  Female
49       Prof  Female
50       Prof  Female

In [61]:
df.loc[[0,1,2],['discipline','rank']]

  discipline       rank
0          B       Prof
1          A       Prof
2          A  AssocProf

In [62]:
df.iloc[::5] # start value:0, end value:77, step value:5, all rows and columns with step value 5

        rank discipline  phd  service     sex  salary
0       Prof          B   56       49    Male  186960
5       Prof          B   17        3    Male  150480
10  AsstProf          B    4        4    Male   92000
15  AsstProf          B    7        2    Male   91300
20      Prof          B   45       45    Male  146856
25  AsstProf          B   11        3  Female   74692
30      Prof          A   12        0  Female  105000
35  AsstProf          B    3        3  Female   92000
40      Prof          A   17       11  Female   90450
45      Prof          B   24       15  Female  161101
50      Prof          A   23       15  Female  109646

In [63]:
df.iloc[10:30:4]

         rank discipline  phd  service     sex  salary
10   AsstProf          B    4        4    Male   92000
14       Prof          A   30       23    Male   91100
18       Prof          B   22       21    Male  155750
22       Prof          A   39       36  Female  137000
26  AssocProf          B   11       11  Female  103613

In [64]:
df.iloc[::-1] # all records in reverse order

         rank discipline  phd  service     sex  salary
50       Prof          A   23       15  Female  109646
49       Prof          A   28       14  Female  109954
48       Prof          B   17       17  Female  124312
47  AssocProf          B   19        6  Female  104542
46       Prof          B   18       10  Female  105450
45       Prof          B   24       15  Female  161101
44  AssocProf          B   12        9  Female   71065
43   AsstProf          A    8        3  Female   78500
42       Prof          A   28        7  Female  116450
41   AsstProf          A    4        2  Female   77500
40       Prof          A   17       11  Female   90450
39   AsstProf          A    7        6  Female   63100
38       Prof          A   36       19  Female  117555
37  AssocProf          A   26       24  Female   73300
36       Prof          A   29       27  Female   91000
35   AsstProf          B    3        3  Female   92000
34  AssocProf          B   12       10  Female  103994
33       Prof          B   36       26  Female  144651
32   AsstProf          A    3        1  Female   72500
31   AsstProf          A    5        3  Female   73500
30       Prof          A   12        0  Female  105000
29       Prof          B   20       14  Female  127512
28   AsstProf          B   10        5  Female   97032
27       Prof          B   17       17  Female  111512
26  AssocProf          B   11       11  Female  103613
25   AsstProf          B   11        3  Female   74692
24       Prof          B   25       25  Female  140096
23  AssocProf          A   13        8  Female   74830
22       Prof          A   39       36  Female  137000
21   AsstProf          B    4        3    Male   91000
20       Prof          B   45       45    Male  146856
19  AssocProf          B   12        8    Male  119800
18       Prof          B   22       21    Male  155750
17  AssocProf          B    9        7    Male  107008
16       Prof          B   21       20    Male  123683
15   AsstProf          B    7        2    Male   91300
14       Prof          A   30       23    Male   91100
13   AsstProf          A    2        0    Male   85000
12   AsstProf          A    4        2    Male   73000
11       Prof          A   33       30    Male  103106
10   AsstProf          B    4        4    Male   92000
9        Prof          A   29       27    Male  150500
8        Prof          A   19        7    Male  107300
7    AsstProf          B    4        0    Male   92000
6    AsstProf          B    8        3    Male   75044
5        Prof          B   17        3    Male  150480
4    AsstProf          B    1        0    Male   88000
3        Prof          B   23       23    Male  134778
2   AssocProf          A   20       17    Male   81285
1        Prof          A   20       20    Male  122400
0        Prof          B   56       49    Male  186960